[package]
name = "toolbox"
version = "1.0.1"
description = "Windows app launcher and management tool"
authors = ["you"]
edition = "2021"

[lib]
name = "toolbox_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["protocol-asset"] }
tauri-plugin-shell = "2"
tauri-plugin-dialog = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
rusqlite = { version = "0.32", features = ["bundled"] }
uuid = { version = "1", features = ["v4"] }
dirs = "5"
image = { version = "0.25", default-features = false, features = ["png"] }
ureq = { version = "3.4.2", default-features = false, features = ["native-tls", "json"] }
base64 = "0.22"
ed25519-dalek = "2"

[target.'cfg(target_os = "windows")'.dependencies]
windows = { version = "0.61", features = [
    "Win32_Foundation",
    "Win32_Graphics_Gdi",
    "Win32_UI_Shell",
    "Win32_UI_WindowsAndMessaging",
    "Win32_UI_Controls",
    "Win32_System_Diagnostics_ToolHelp",
    "Win32_System_Registry",
    "Win32_Storage_FileSystem",
] }

[dev-dependencies]
tempfile = "3"

[profile.release]
panic = "abort"
codegen-units = 1
lto = true
opt-level = "s"
strip = true
